### ISSUE TITLE
Wrong URL for libspatialite

### ISSUE THREAD

**Issue by karzelek-hi** [gstf/libspatialite-ios#10]
The make script runs

```bash
curl http://www.gaia-gis.it/gaia-sins/libspatialite-4.2.0.tar.gz > spatialite.tar.gz
```
But that URL does not exist. Checked on the gaia web site, seems it needs to be now 
```bash
curl http://www.gaia-gis.it/gaia-sins/libspatialite-sources/libspatialite-4.2.0.zip > spatialite.tar.gz
```

**Comment by muellermartin** [comment]
Confirmed, I'm about to update the link. There also seems to be a new version (4.3.0) available, so I will use this instead to include latest fixes etc.

Note: You used the ZIP archive, but I prefer the gzipped (or bzipped version if available) to save bandwith for everybody ;)
