### ISSUE TITLE
error during the build process

### ISSUE THREAD

**Issue by ddurgaprasad** [gstf/libspatialite-ios#16]
Make builds gets,pros,sqlite without problem.But fails at the end with below errors

ld: warning: ignoring file /usr/local/lib/libxml2.dylib, file was built for x86_64 which is not the architecture being linked (armv7): /usr/local/lib/libxml2.dylib
Undefined symbols for architecture armv7:
  "_xmlAddChild", referenced from:
      _setIsoId in libspatialite.a(gg_xml.o)
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlAddNextSibling", referenced from:
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlAddPrevSibling", referenced from:
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlCleanupParser", referenced from:
      _spatialite_shutdown in libspatialite.a(alloc_cache.o)
  "_xmlDocDumpFormatMemory", referenced from:
      _gaiaXmlLoad in libspatialite.a(gg_xml.o)
      _setIsoId in libspatialite.a(gg_xml.o)
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlDocGetRootElement", referenced from:
      _sniff_payload in libspatialite.a(gg_xml.o)
      _retrieve_iso_identifiers in libspatialite.a(gg_xml.o)
      _retrieve_sld_identifiers in libspatialite.a(gg_xml.o)
      _retrieve_sld_se_identifiers in libspatialite.a(gg_xml.o)
      _gaiaXmlFormat in libspatialite.a(gg_xml.o)
      _setIsoId in libspatialite.a(gg_xml.o)
      _addIsoId in libspatialite.a(gg_xml.o)
      ...
  "_xmlFree", referenced from:
      _gaiaXmlBlobSetFileId in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobSetParentId in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobAddFileId in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobAddParentId in libspatialite.a(gg_xml.o)
  "_xmlFreeDoc", referenced from:
      _splite_free_xml_schema_cache_item in libspatialite.a(gg_xml.o)
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlTextFromBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlFromBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlLoad in libspatialite.a(gg_xml.o)
      _gaiaXmlGetInternalSchemaURI in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobSetFileId in libspatialite.a(gg_xml.o)
      ...
  "_xmlFreeNode", referenced from:
      _setIsoId in libspatialite.a(gg_xml.o)
  "_xmlInitParser", referenced from:
      _spatialite_initialize in libspatialite.a(alloc_cache.o)
  "_xmlNanoHTTPCleanup", referenced from:
      _reset_wfs_http_connection in libspatialite.a(wfs_in.o)
  "_xmlNewNode", referenced from:
      _setIsoId in libspatialite.a(gg_xml.o)
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlNewNs", referenced from:
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlNewText", referenced from:
      _setIsoId in libspatialite.a(gg_xml.o)
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlReadFile", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlLoad in libspatialite.a(gg_xml.o)
      _load_from_wfs_paged in libspatialite.a(wfs_in.o)
      _load_wfs_schema in libspatialite.a(wfs_in.o)
      _test_wfs_paging in libspatialite.a(wfs_in.o)
      _create_wfs_catalog in libspatialite.a(wfs_in.o)
  "_xmlReadMemory", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlTextFromBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlFromBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlGetInternalSchemaURI in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobSetFileId in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobSetParentId in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobAddFileId in libspatialite.a(gg_xml.o)
      ...
  "_xmlReplaceNode", referenced from:
      _setIsoId in libspatialite.a(gg_xml.o)
  "_xmlSchemaFree", referenced from:
      _splite_free_xml_schema_cache_item in libspatialite.a(gg_xml.o)
  "_xmlSchemaFreeParserCtxt", referenced from:
      _splite_free_xml_schema_cache_item in libspatialite.a(gg_xml.o)
  "_xmlSchemaFreeValidCtxt", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
  "_xmlSchemaNewDocParserCtxt", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
  "_xmlSchemaNewValidCtxt", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
  "_xmlSchemaParse", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
  "_xmlSchemaValidateDoc", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
  "_xmlSearchNs", referenced from:
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlSearchNsByHref", referenced from:
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlSetGenericErrorFunc", referenced from:
      _gaiaXmlToBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlTextFromBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlFromBlob in libspatialite.a(gg_xml.o)
      _gaiaXmlLoad in libspatialite.a(gg_xml.o)
      _gaiaXmlGetInternalSchemaURI in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobSetFileId in libspatialite.a(gg_xml.o)
      _gaiaXmlBlobSetParentId in libspatialite.a(gg_xml.o)
      ...
  "_xmlSetNs", referenced from:
      _addIsoId in libspatialite.a(gg_xml.o)
  "_xmlXPathCompile", referenced from:
      _gaiaIsValidXPathExpression in libspatialite.a(libsplite_la-virtualxpath.o)
  "_xmlXPathEvalExpression", referenced from:
      _vxpath_eval_expr in libspatialite.a(libsplite_la-virtualxpath.o)
  "_xmlXPathFreeCompExpr", referenced from:
      _gaiaIsValidXPathExpression in libspatialite.a(libsplite_la-virtualxpath.o)
  "_xmlXPathFreeContext", referenced from:
      _gaiaXmlGetInternalSchemaURI in libspatialite.a(gg_xml.o)
      _vxpath_eval_expr in libspatialite.a(libsplite_la-virtualxpath.o)
      _vxpath_close in libspatialite.a(libsplite_la-virtualxpath.o)
      _vxpath_read_row in libspatialite.a(libsplite_la-virtualxpath.o)
  "_xmlXPathFreeObject", referenced from:
      _gaiaXmlGetInternalSchemaURI in libspatialite.a(gg_xml.o)
      _vxpath_eval_expr in libspatialite.a(libsplite_la-virtualxpath.o)
      _vxpath_close in libspatialite.a(libsplite_la-virtualxpath.o)
      _vxpath_read_row in libspatialite.a(libsplite_la-virtualxpath.o)
  "_xmlXPathNewContext", referenced from:
      _vxpath_eval_expr in libspatialite.a(libsplite_la-virtualxpath.o)
  "_xmlXPathRegisterNs", referenced from:
      _vxpath_eval_expr in libspatialite.a(libsplite_la-virtualxpath.o)
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[4]: *** [demo1] Error 1
make[3]: *** [install-recursive] Error 1
make[2]: *** [install-strip] Error 2
make[1]: *** [/Users/admin/Downloads/gstf/libspatialite-ios/build/armv7/lib/libspatialite.a] Error 2
make: *** [build_arches] Error 2

**Comment by adolby** [comment]
Fixed by #17. This error occurs because libspatialite now depends on libxml2 by default. You can specify --enable-libxml2=no as the Makefile now does or you could build libxml2 in the Makefile if you want to be able to use the features in libspatialite that require libxml2. You can see these features by function at the [SQL functions reference list](http://www.gaia-gis.it/gaia-sins/spatialite-sql-4.3.0.html).

**Comment by gstf** [comment]
Closing. @ddurgaprasad If the problem still exists please reopen.
