### ISSUE TITLE
tar: Unrecognized archive format

### ISSUE THREAD

**Issue by YangZhou91** [gstf/libspatialite-ios#4]
tar -xzf spatialite.tar.gz
tar: Unrecognized archive format
tar: Error exit delayed from previous errors.
make[1]: *** [/Users/Gavin/Desktop/libspatialite-ios/spatialite] Error 1
make: *** [build_arches] Error 2

Xcode 6.2 with command tool installed.

**Comment by muellermartin** [comment]
A quick look revealed that the URL to libspatialite returns a HTTP 404 error. Thus the URL needs to be fixed.

**Comment by muellermartin** [comment]
Should be fixed in commit f0c3b3c
