### ISSUE TITLE
64bit arm support

### ISSUE THREAD

**Issue by DavidTomic** [gstf/libspatialite-ios#5]
Hi!

Can you update MakeFile to support arm64 ?

I tried myself but cannot get it working.

Tnx

**Comment by florean** [comment]
Can you explain why it wasn't working?  I had a little trouble, but got it to work.  Try it for yourself:
https://github.com/florean/libspatialite-ios

I'm really curious whether or not the last two lines adding "-Wno-error=implicit-function-declaration" are really necessary or some bug in my environment.

**Comment by muellermartin** [comment]
I tried to add arm64 myself after this issue was created but I also failed on the error complaining about ``implicit declaration of function 'locale_charset`` in ``gg_utf8.c`` while compiling libspatialite.

Currently I'm reviewing your pull request (#6) which seems quite promising…

**Comment by muellermartin** [comment]
Implemented in d76703f.
